DROP TABLE IF EXISTS TBL_EMPLOYEES;
DROP TABLE IF EXISTS FAVORITE;
 
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE FAVORITE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  key1 VARCHAR(250) NOT NULL,
  key2 VARCHAR(250) NOT NULL,
  key3 VARCHAR(250) DEFAULT NULL
);